#include "drayven/Drys.hpp"
#include <fstream>
#include <sstream>
#include <unordered_map>
#include <algorithm>
#include <cctype>

namespace drayven::drys {
static std::string trim(std::string s){auto a=s.find_first_not_of(" \t\r");if(a==std::string::npos)return{};auto b=s.find_last_not_of(" \t\r");return s.substr(a,b-a+1);}
static bool starts(const std::string& s,const std::string& p){return s.rfind(p,0)==0;}
static std::string sanitize(std::string s){for(char&c:s)if(!std::isalnum((unsigned char)c)&&c!='_')c='_';if(s.empty()||std::isdigit((unsigned char)s[0]))s="_"+s;return s;}
static std::string expr(std::string s){
    static const std::unordered_map<std::string,std::string> calls={
        {"log(","drayven::script::log("},{"key_down(","drayven::script::keyDown("},{"key_pressed(","drayven::script::keyPressed("},
        {"move_x(","drayven::script::moveX("},{"move_y(","drayven::script::moveY("},{"set_position(","drayven::script::setPosition("},
        {"play_sound(","drayven::script::playSound("},{"spawn(","drayven::script::spawn("},{"destroy(","drayven::script::destroy("},
        {"delta_time(","drayven::script::deltaTime("},{"rand(","drayven::script::random("}
    };
    for(auto& [a,b]:calls){std::size_t p=0;while((p=s.find(a,p))!=std::string::npos){s.replace(p,a.size(),b);p+=b.size();}}
    std::size_t p=0;while((p=s.find(" and ",p))!=std::string::npos)s.replace(p,5," && ");p=0;while((p=s.find(" or ",p))!=std::string::npos)s.replace(p,4," || ");
    if(starts(s,"not "))s="!"+s.substr(4); return s;
}
TranspileResult Transpiler::transpile(std::string_view source,std::string_view moduleName) const {
    TranspileResult r; std::stringstream in{std::string(source)}; std::ostringstream globals,body; std::string line; int lineNo=0,indent=1; std::vector<std::string> stack; std::string game=sanitize(std::string(moduleName)); bool inFn=false;
    while(std::getline(in,line)){++lineNo; auto t=trim(line); if(t.empty()||starts(t,"#")||starts(t,"//"))continue;
        if(starts(t,"game ")){game=sanitize(trim(t.substr(5)));continue;}
        if(starts(t,"import "))continue;
        if(starts(t,"var ")||starts(t,"let ")){auto rest=trim(t.substr(4));auto eq=rest.find('=');std::string name=trim(eq==std::string::npos?rest:rest.substr(0,eq));std::string val=eq==std::string::npos?"0":expr(trim(rest.substr(eq+1))); if(!inFn)globals<<"    drayven::script::Value "<<sanitize(name)<<" = "<<val<<";\n";else body<<std::string(indent*4,' ')<<"auto "<<sanitize(name)<<" = "<<val<<";\n";continue;}
        if(starts(t,"fn ")){auto sig=trim(t.substr(3));auto p=sig.find('(');auto q=sig.rfind(')');if(p==std::string::npos||q==std::string::npos||q<p){r.ok=false;r.diagnostics.push_back("line "+std::to_string(lineNo)+": invalid function declaration");continue;}auto name=sanitize(trim(sig.substr(0,p)));auto args=sig.substr(p+1,q-p-1);std::stringstream as(args);std::string a;std::vector<std::string> argv;while(std::getline(as,a,',')){a=trim(a);if(!a.empty())argv.push_back("double "+sanitize(a));}body<<"    void "<<name<<"(";for(size_t i=0;i<argv.size();++i){if(i)body<<", ";body<<argv[i];}body<<") {\n";indent=2;stack.push_back("fn");inFn=true;continue;}
        if(t=="end"){if(stack.empty()){r.ok=false;r.diagnostics.push_back("line "+std::to_string(lineNo)+": unexpected end");continue;}--indent;body<<std::string(indent*4,' ')<<"}\n";auto s=stack.back();stack.pop_back();if(s=="fn")inFn=false;continue;}
        if(starts(t,"if ")){body<<std::string(indent*4,' ')<<"if ("<<expr(trim(t.substr(3)))<<") {\n";++indent;stack.push_back("if");continue;}
        if(t=="else"){if(stack.empty()||stack.back()!="if"){r.ok=false;r.diagnostics.push_back("line "+std::to_string(lineNo)+": else without if");continue;}--indent;body<<std::string(indent*4,' ')<<"} else {\n";++indent;continue;}
        if(starts(t,"while ")){body<<std::string(indent*4,' ')<<"while ("<<expr(trim(t.substr(6)))<<") {\n";++indent;stack.push_back("while");continue;}
        if(starts(t,"return")){body<<std::string(indent*4,' ')<<"return";auto rest=trim(t.substr(6));if(!rest.empty())body<<" "<<expr(rest);body<<";\n";continue;}
        std::string st=expr(t); if(!st.empty()&&st.back()!=';')st+=';'; body<<std::string(indent*4,' ')<<st<<"\n";
    }
    if(!stack.empty()){r.ok=false;r.diagnostics.push_back("unclosed block at end of file");}
    std::ostringstream out;out<<"// Generated by Drayven Script (DRYS). Do not edit.\n#include <drayven/ScriptAPI.hpp>\n\nnamespace drayven::generated {\nclass "<<game<<" final {\npublic:\n"<<globals.str()<<body.str()<<"};\n}\n";r.cpp=out.str();return r;
}
TranspileResult Transpiler::transpileFile(const std::filesystem::path& source) const {std::ifstream in(source);if(!in)return{false,"",{"cannot open "+source.string()}};std::stringstream ss;ss<<in.rdbuf();return transpile(ss.str(),source.stem().string());}
}
