include(FetchContent)
function(drayven_setup_dependencies)
  if(NOT DRAYVEN_FETCH_DEPS)
    find_package(SDL3 CONFIG REQUIRED)
    find_package(OpenGL REQUIRED)
  else()
    if(ANDROID)
      set(SDL_SHARED OFF CACHE BOOL "" FORCE)
      set(SDL_STATIC ON CACHE BOOL "" FORCE)
    else()
      set(SDL_SHARED ON CACHE BOOL "" FORCE)
      set(SDL_STATIC OFF CACHE BOOL "" FORCE)
    endif()
    set(SDL_TEST_LIBRARY OFF CACHE BOOL "" FORCE)
    set(SDL_TESTS OFF CACHE BOOL "" FORCE)
    set(SDL_EXAMPLES OFF CACHE BOOL "" FORCE)
    set(SDL_INSTALL OFF CACHE BOOL "" FORCE)
    FetchContent_Declare(SDL3 GIT_REPOSITORY https://github.com/libsdl-org/SDL.git GIT_TAG release-3.4.12 GIT_SHALLOW TRUE)
    FetchContent_MakeAvailable(SDL3)
  endif()
  if(NOT ANDROID)
    find_package(OpenGL REQUIRED)
  endif()
  if(DRAYVEN_BUILD_EDITOR)
    if(NOT DRAYVEN_FETCH_DEPS)
      find_package(Freetype REQUIRED)
      find_package(RmlUi 6.2 CONFIG REQUIRED)
      message(FATAL_ERROR "DRAYVEN_FETCH_DEPS=OFF currently requires DRAYVEN_RMLUI_SOURCE_DIR to point at an RmlUi 6.2 source checkout for the lightweight SDL3 backend.")
    endif()
    set(FT_DISABLE_ZLIB ON CACHE BOOL "" FORCE)
    set(FT_DISABLE_BZIP2 ON CACHE BOOL "" FORCE)
    set(FT_DISABLE_PNG ON CACHE BOOL "" FORCE)
    set(FT_DISABLE_HARFBUZZ ON CACHE BOOL "" FORCE)
    set(FT_DISABLE_BROTLI ON CACHE BOOL "" FORCE)
    FetchContent_Declare(freetype GIT_REPOSITORY https://github.com/freetype/freetype.git GIT_TAG VER-2-14-3 GIT_SHALLOW TRUE)
    FetchContent_MakeAvailable(freetype)
    if(TARGET freetype AND NOT TARGET Freetype::Freetype)
      add_library(Freetype::Freetype ALIAS freetype)
    endif()
    set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
    set(RMLUI_SAMPLES OFF CACHE BOOL "" FORCE)
    set(RMLUI_TESTS OFF CACHE BOOL "" FORCE)
    set(RMLUI_FONT_ENGINE freetype CACHE STRING "" FORCE)
    set(RMLUI_LUA_BINDINGS OFF CACHE BOOL "" FORCE)
    set(RMLUI_SVG_PLUGIN OFF CACHE BOOL "" FORCE)
    set(RMLUI_LOTTIE_PLUGIN OFF CACHE BOOL "" FORCE)
    set(RMLUI_PRECOMPILED_HEADERS ON CACHE BOOL "" FORCE)
    FetchContent_Declare(rmlui GIT_REPOSITORY https://github.com/mikke89/RmlUi.git GIT_TAG 6.2 GIT_SHALLOW TRUE)
    FetchContent_MakeAvailable(rmlui)
    set(DRAYVEN_RMLUI_SOURCE_DIR "${rmlui_SOURCE_DIR}" PARENT_SCOPE)
  endif()
  if(DRAYVEN_ENABLE_EIGEN)
    if(DRAYVEN_FETCH_DEPS)
      set(EIGEN_BUILD_DOC OFF CACHE BOOL "" FORCE)
      set(BUILD_TESTING OFF CACHE BOOL "" FORCE)
      FetchContent_Declare(eigen GIT_REPOSITORY https://gitlab.com/libeigen/eigen.git GIT_TAG 3.4.0 GIT_SHALLOW TRUE)
      FetchContent_MakeAvailable(eigen)
    else()
      find_package(Eigen3 3.4 CONFIG REQUIRED)
    endif()
  endif()
  if(DRAYVEN_ENABLE_NETWORKING)
    if(DRAYVEN_FETCH_DEPS)
      set(BUILD_CURL_EXE OFF CACHE BOOL "" FORCE)
      set(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
      set(BUILD_LIBCURL_DOCS OFF CACHE BOOL "" FORCE)
      set(BUILD_MISC_DOCS OFF CACHE BOOL "" FORCE)
      set(HTTP_ONLY ON CACHE BOOL "" FORCE)
      set(CURL_USE_LIBPSL OFF CACHE BOOL "" FORCE)
      set(CURL_ZLIB OFF CACHE BOOL "" FORCE)
      set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
      FetchContent_Declare(curl GIT_REPOSITORY https://github.com/curl/curl.git GIT_TAG curl-8_20_0 GIT_SHALLOW TRUE)
      FetchContent_MakeAvailable(curl)
    else()
      find_package(CURL REQUIRED)
    endif()
  endif()
  if(DRAYVEN_ENABLE_MBEDTLS)
    if(DRAYVEN_FETCH_DEPS)
      set(ENABLE_PROGRAMS OFF CACHE BOOL "" FORCE)
      set(ENABLE_TESTING OFF CACHE BOOL "" FORCE)
      set(USE_SHARED_MBEDTLS_LIBRARY OFF CACHE BOOL "" FORCE)
      set(USE_STATIC_MBEDTLS_LIBRARY ON CACHE BOOL "" FORCE)
      FetchContent_Declare(mbedtls GIT_REPOSITORY https://github.com/Mbed-TLS/mbedtls.git GIT_TAG mbedtls-3.6.7 GIT_SHALLOW TRUE GIT_SUBMODULES_RECURSE TRUE)
      FetchContent_MakeAvailable(mbedtls)
    else()
      find_package(MbedTLS REQUIRED)
    endif()
  endif()
  if(DRAYVEN_ENABLE_VULKAN)
    find_package(Vulkan QUIET)
    if(Vulkan_FOUND)
      message(STATUS "Drayven: Vulkan SDK found")
    else()
      message(STATUS "Drayven: Vulkan SDK not found; OpenGL runtime remains available")
    endif()
  endif()
endfunction()
