function(drayven_add_game target)
  cmake_parse_arguments(DG "" "SOURCE_DIR;PROJECT_FILE" "SOURCES" ${ARGN})
  if(NOT DG_SOURCE_DIR)
    set(DG_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR})
  endif()
  add_executable(${target} ${DG_SOURCES})
  target_link_libraries(${target} PRIVATE DrayvenRuntime)
  target_include_directories(${target} PRIVATE ${DG_SOURCE_DIR})
  target_compile_definitions(${target} PRIVATE DRAYVEN_GAME_PROJECT=\"${DG_PROJECT_FILE}\")
endfunction()
